#!/usr/bin/env bash
# commit-guard — pre-push enforcement for meet-biscuit.
#
# SOURCE OF TRUTH: .claude/agents/commit-guard.md (the agent spec). This script
# is the executable mirror of that file — when the .md rules change (allowlist,
# patterns, identities), regenerate/sync this script to match. Rule rationale
# also lives in the private guide
#   ~/dev/projectguidefordev/mdcc-basecamp-2026/CLAUDE.md
# This script just enforces the rules automatically so a bad push can't slip out.
#
# HARD checks (block the push, exit 1):
#   1. author email must be the ba-00001 noreply address
#   2. no AI/tool/bot attribution in commit messages being pushed
#   3. every commit's author + committer is "Brian Bazurto" <ba-00001 noreply>
# SOFT checks (warn only):
#   4. attribution-specific words in added diff lines, outside the .claude/ allowlist
#
# Installed as .git/hooks/pre-push by scripts/install-git-hooks.sh.
# Override in a pinch with:  git push --no-verify

set -uo pipefail

EXPECTED_EMAIL="124537281+ba-00001@users.noreply.github.com"
ZERO="0000000000000000000000000000000000000000"
fail=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
grn() { printf '\033[32m%s\033[0m\n' "$1"; }
ylw() { printf '\033[33m%s\033[0m\n' "$1"; }

# --- figure out which commits are being pushed -----------------------------
# pre-push feeds "<local_ref> <local_sha> <remote_ref> <remote_sha>" on stdin.
# Run by hand (tty) it falls back to "everything not yet on origin".
ranges=()
if [ ! -t 0 ]; then
  while read -r local_ref local_sha remote_ref remote_sha; do
    [ -z "${local_sha:-}" ] && continue
    [ "$local_sha" = "$ZERO" ] && continue            # branch deletion
    if [ "${remote_sha:-$ZERO}" = "$ZERO" ]; then
      ranges+=("$local_sha --not --remotes=origin")   # new branch
    else
      # Everything already on an origin ref is excluded, not just what is on the
      # branch being pushed. A branch that has been rebased onto (or merged with)
      # main drags main's commits into remote_sha..local_sha, and a merge commit
      # GitHub itself wrote when a PR was merged in the web UI is authored
      # "GitHub <noreply@github.com>" — which this guard then blocks, on a commit
      # nobody in this session wrote and that is already public. Vetting is for
      # what the push actually adds.
      ranges+=("$remote_sha..$local_sha --not --remotes=origin")
    fi
  done
fi
if [ ${#ranges[@]} -eq 0 ]; then
  if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    ranges+=("@{u}..HEAD --not --remotes=origin")
  else
    ranges+=("HEAD --not --remotes=origin")
  fi
fi
# shellcheck disable=SC2086
commits="$(for r in "${ranges[@]}"; do git rev-list $r; done 2>/dev/null | sort -u)"

# --- 1. author email (HARD) ------------------------------------------------
email="$(git config user.email || true)"
if [ "$email" != "$EXPECTED_EMAIL" ]; then
  red "HARD FAIL · author email is '$email' (expected $EXPECTED_EMAIL)"
  echo "    fix: git config user.email \"$EXPECTED_EMAIL\""
  fail=1
fi

if [ -z "$commits" ]; then
  [ "$fail" -eq 0 ] && grn "commit-guard: no new commits to scan; email OK"
  exit "$fail"
fi

# --- 2. forbidden attribution in commit messages (HARD) --------------------
# AI-name tokens are matched as ATTRIBUTION only: a leading (^|[^.[:alnum:]])
# guard means a preceding dot or letter excludes them, so the literal ".claude/"
# config-dir path in a message/diff is NOT flagged, but "Claude Code" / "by
# Claude" / a co-author trailer still is.
# "generated with/by" is anchored to line start: an attribution trailer is
# always its own line, while mid-sentence prose ("the page is generated by
# gen_student_volunteer_page.py") is describing site tooling, not authorship.
# Mid-line uses still surface as SOFT warns via the diff scan below.
MSG_PAT='co-authored-by:|^[[:space:]]*(auto-)?generated (with|by)|auto-generated file|🤖|🦾|\[bot\]|(^|[^.[:alnum:]])(claude|anthropic|chatgpt|gpt-|copilot|llm|assistant)'
while read -r c; do
  [ -z "$c" ] && continue
  hits="$(git log -1 --format='%s%n%b' "$c" | grep -iEn "$MSG_PAT" || true)"
  if [ -n "$hits" ]; then
    red "HARD FAIL · forbidden attribution in commit ${c:0:9} message"
    printf '%s\n' "$hits" | sed 's/^/    /'
    fail=1
  fi
done <<< "$commits"

# --- 3. author / committer identity (HARD) ---------------------------------
ID_OK='^Brian Bazurto <124537281\+ba-00001@users\.noreply\.github\.com>$'
while read -r c; do
  [ -z "$c" ] && continue
  while read -r who; do
    if ! printf '%s' "$who" | grep -qE "$ID_OK"; then
      red "HARD FAIL · disallowed identity in commit ${c:0:9}: $who"
      echo "    fix: reauthor to 'Brian Bazurto <$EXPECTED_EMAIL>'"
      fail=1
    fi
  done < <(git log -1 --format='%an <%ae>%n%cn <%ce>' "$c")
done <<< "$commits"

# --- 4. SOFT: attribution words in added diff lines (.claude/ allowlisted)
# Agent specs under .claude/ and this script's own patterns name assistants as
# subject matter, not authorship.
ALLOW='^(\.claude/|scripts/commit-guard\.sh$)'
DIFF_PAT='co-authored-by:|🤖|🦾|generated with|generated by|auto-generated|(^|[^.[:alnum:]])(claude|anthropic|copilot)'
# One awk pass per commit. This used to run two subprocesses per added line,
# which on a 20k-line push meant ~40k spawns and a push that looked hung.
# DIFF_PAT is all lower-case, so lower-casing the line matches case-insensitively.
while read -r c; do
  [ -z "$c" ] && continue
  git show --format= --unified=0 "$c" | awk -v pat="$DIFF_PAT" -v allow="$ALLOW" '
    /^diff --git a\// { f = $0; sub(/^diff --git a\//, "", f); sub(/ b\/.*$/, "", f); next }
    /^\+\+\+/ { next }
    /^\+/ {
      if (tolower($0) ~ pat && f !~ allow) {
        printf "SOFT WARN · %s: %s\n", f, substr(substr($0, 2), 1, 80)
      }
    }' | while IFS= read -r warn; do ylw "$warn"; done
done <<< "$commits"

if [ "$fail" -eq 1 ]; then
  red "commit-guard: PUSH BLOCKED — fix the HARD FAILs above (or 'git push --no-verify')."
  exit 1
fi
grn "commit-guard: PASS"
exit 0
